"""empty message

Revision ID: eabd6ad9a06d
Revises: d20c6fa17ea2
Create Date: 2024-11-28 13:03:37.552284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eabd6ad9a06d'
down_revision = 'd20c6fa17ea2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fornecedora', schema=None) as batch_op:
        batch_op.alter_column('cidade',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fornecedora', schema=None) as batch_op:
        batch_op.alter_column('cidade',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
